CREATE TABLE IF NOT EXISTS sensor
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL,
    model       VARCHAR(255) NOT NULL,
    range_from  INTEGER      NOT NULL,
    range_to    INTEGER      NOT NULL,
    type_name   VARCHAR(255),
    unit_name   VARCHAR(255),
    description VARCHAR(255),
    location    VARCHAR(255),
    PRIMARY KEY (id)
);

ALTER TABLE sensor
    ADD CONSTRAINT sensor_type
        FOREIGN KEY (type_name)
            REFERENCES type;

ALTER TABLE sensor
    ADD CONSTRAINT sensor_unit
        FOREIGN KEY (unit_name)
            REFERENCES unit;